config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bills/index'

  get 'bills/add'

	get 'viewall/alumni'

  get 'viewall/students'

  get 'viewall/alumni/paid' => 'viewall#paid'

  get 'viewall/alumni/:year' => 'viewall#year'

  get 'alumni_data/update'

  get 'alumni/index'

  get 'alumni/show'

  get 'student_member/index'

  get 'student_member/show'

  devise_for :coordinators
  devise_for :student_members
  devise_for :registered_alumnis, controllers: { sessions: "registered_alumnis/sessions", registrations: "registered_alumnis/registrations" }

  resources :student_member
  resources :alumni
  resource :alumni_datum
  resource :sponsors

  get 'sponsors/update/:id' => 'sponsors#update'
  get 'sponsors/view/:id' => 'sponsors#view'
  post 'sponsors/edit/:id' => 'sponsors#edit'

  get '/homepage' => 'staticpage#index'
  get '/homepage/studentmember' => 'student_member#index'
  get '/homepage/coordinator' => 'coordinator#index'
  get '/information' => 'registered_alumni#show'

  get '/data/administrator/createallusers' => 'staticpage#createallusers'
  get '/data/administrator/addmorealumni' => 'data#addmore'
  get '/data/administrator/backup' => 'data#backup'

  get 'allotment/allot' => 'allotment#allot'

  post '/alumni/status/search' => 'alumni_status#updatesearch'
  post '/alumni/status/response' => 'alumni_status#updateresponse'

  root 'routing#index'

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
	def index
	end

	def createallusers

		StudentMember.create(id: '0',
			name: 'Default User', 
			rollnum: '15DF12345',
			portfolio: 'Default Portfolio',
			email: 'student@example.com', 
			password: 'password', 
			password_confirmation: 'password')

		Coordinator.create(id: '0',
			name: 'Default User',
			rollnum: '15DF12346',
			portfolio: 'Default Portfolio',
			email: 'coordinator@example.com', 
			password: 'password', 
			password_confirmation: 'password')

		# for i in 0..10
		# 	a = Alumni.new
		# 	a.name = "Something " + i.to_s
		# 	a.hall = "DF"
		# 	a.department = "FH"
		# 	a.year = "1966"
		# 	a.save!
		# end

		render(:file => File.join(Rails.root, 'public/201.html'), :status => 201, :layout => false)
		return
		
	end
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/staticpage/createallusers.html.erb
<h1>
	The records were probably created.
</h1>

app/views/staticpage/index.html.erb
<br>
<br>
<div class="container-fluid" style="text-align: center; ">
	<div class="col-md-5">
		<a href="<%= new_student_member_session_path %>">
			<button class="btn btn-lg btn-success">
				Login as Student Member
			</button>
		</a>
		<br/>
		<br>
		<a href="<%= new_student_member_registration_path %>">
			<button class="btn btn-lg btn-info">
				Register as a Student Member
			</button>
		</a>
	</div>
	<div class="col-md-2">
		
	</div>
	<div class="col-md-5">
		<a href="<%= new_coordinator_session_path %>">
			<button class="btn btn-lg btn-success">
				Login as Coordinator
			</button>
		</a>
		<br>
		<br>
		<a href="<%= new_coordinator_registration_path %>">
			<button class="btn btn-lg btn-info">
				Register as a Coordinator
			</button>
		</a>
	</div>
</div>