config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bills/index'

  get 'bills/add'

	get 'viewall/alumni'

  get 'viewall/students'

  get 'viewall/alumni/paid' => 'viewall#paid'

  get 'viewall/alumni/:year' => 'viewall#year'

  get 'alumni_data/update'

  get 'alumni/index'

  get 'alumni/show'

  get 'student_member/index'

  get 'student_member/show'

  devise_for :coordinators
  devise_for :student_members
  devise_for :registered_alumnis, controllers: { sessions: "registered_alumnis/sessions", registrations: "registered_alumnis/registrations" }

  resources :student_member
  resources :alumni
  resource :alumni_datum
  resource :sponsors

  get 'sponsors/update/:id' => 'sponsors#update'
  get 'sponsors/view/:id' => 'sponsors#view'
  post 'sponsors/edit/:id' => 'sponsors#edit'

  get '/homepage' => 'staticpage#index'
  get '/homepage/studentmember' => 'student_member#index'
  get '/homepage/coordinator' => 'coordinator#index'
  get '/information' => 'registered_alumni#show'

  get '/data/administrator/createallusers' => 'staticpage#createallusers'
  get '/data/administrator/addmorealumni' => 'data#addmore'
  get '/data/administrator/backup' => 'data#backup'

  get 'allotment/allot' => 'allotment#allot'

  post '/alumni/status/search' => 'alumni_status#updatesearch'
  post '/alumni/status/response' => 'alumni_status#updateresponse'

  root 'routing#index'

end

app/models/alumni.rb
class Alumni < ActiveRecord::Base
	has_one :AlumniStatus
	has_one :AlumniData
	has_one :TieAlumniWithStudentMember
	after_create :build_other_records
	before_destroy { |record| AlumniStatus.destroy_all "alumni_id = #{record.id}"   }
	before_destroy { |record| AlumniData.destroy_all "alumni_id = #{record.id}"   }
	before_destroy { |record| TieAlumniWithStudentMember.destroy_all "alumni_id = #{record.id}"   }

	comma do
		id "ID"
		name
		year "Graduation year"
		department
		hall "Hall"

    AlumniData :company
    AlumniData :designation
    AlumniData :home_address => "Home Address"
    AlumniData :office_address
    AlumniData :home_phone
    AlumniData :office_phone
    AlumniData :mobile_phone
    AlumniData :email1 => "Primary Email"
    AlumniData :email2 => "Secondary Email"
    AlumniData :payment_details
    AlumniData :call_next_at

    AlumniStatus  :search
    AlumniStatus  :response

    TieAlumniWithStudentMember :studentmember_id
	end

	private
	def build_other_records
		AlumniStatus.create({ :alumni_id => self.id })
		AlumniData.create({ :alumni_id => self.id })
		TieAlumniWithStudentMember.create({ :alumni_id => self.id, :studentmember_id => 0})
		true
	end
end

app/controllers/alumni_controller.rb
class AlumniController < ApplicationController

  def show

    ensure_signed_in

  	@thisID = params[:id]
    @alum = Alumni.select("*").joins(:AlumniData, :AlumniStatus, :TieAlumniWithStudentMember).find(@thisID)
  	# @alum = Alumni.find(@thisID)
  	# @astat = AlumniStatus.find_by_alumni_id(@thisID)

  	@alumni_data = AlumniData.find_by_alumni_id(@thisID)

    @editingAllowed = false
    @assignedtoid = -1

    if @tie = TieAlumniWithStudentMember.find_by_alumni_id(@thisID)
      @assignedtoid = @tie.studentmember_id
      if student_member_signed_in? && @assignedtoid == current_student_member.id
        @editingAllowed = true
      end
    else
      render plain: "This alumni has not been allotted to anyone yet. Contact the SysAdmin."
    end

  	# render plain: @alumni_data.inspect

  	# render plain: @astat.inspect
  end
end

app/helpers/alumni_helper.rb
module AlumniHelper
end

app/views/alumni/show.html.erb
<style type="text/css">
li:hover{
	cursor: pointer;
}
</style>

<h1>Profile page for Alumni ID <%= @thisID %> </h1>

<h3> <%= @alum.name %> </h3>
<h3> <%= @alum.hall %> Hall </h3>
<h3> <%= @alum.year %> Batch </h3>

<h2> Status Information </h2>

<h3> Search: </h3>

<ul class="setsearch nav nav-pills">
	<li role="presentation" data-val-integer="3" data-val="dumped"><a>Dumped</a></li>
	<li role="presentation" data-val-integer="2" data-val="tobesearched"><a>To-be-searched</a></li>
	<li role="presentation" data-val-integer="1" data-val="found"><a>Found</a></li>
	<li role="presentation" data-val-integer="0" data-val="ready"><a>Ready</a></li>
</ul>

<% if @alum.response == "verified" %>

<h3 class="alert alert-success">Payment verified</h3>

<% else %>

<h3> Calling: </h3>

<ul class="setresponse nav nav-pills">

	<li role="presentation" data-val-integer="1" data-val="negative"><a>Negative</a></li>
	<li role="presentation" data-val-integer="2" data-val="neutral"><a>Neutral</a></li>
	<li role="presentation" data-val-integer="0" data-val="positive"><a>Positive</a></li>
	<li role="presentation" data-val-integer="3" data-val="registered"><a>Registered</a></li>
	<li role="presentation" data-val-integer="4" data-val="paid"><a>Paid</a></li>

	<% if coordinator_signed_in? %>
	<li role="presentation" data-val-integer="5" data-val="verified"><a>Verify payment</a></li>
	<% end %>

</ul>

<% end %>

<div id="payment_details_div">
	<h3>Payment Details</h3>
	<p id="mode">Mode: </p>
	<p id="refnum">Reference Number: </p>
	<p id="date">Date: </p>
	<p id="amount">Amount: </p>
	<p id="bank">Bank: </p>
	<p id="branch">Branch: </p>
	<p id="others">Others: </p>
</div>

<h3> 

	<% if @assignedtoid > 0 %>

	Assigned to <%= StudentMember.find(@assignedtoid).name %> (ID <%= @assignedtoid %>)

	<% else %>

	Not assigned to any Student Member. Contact SysAdmin for assigning this Alumni.

	<% end %>

</h3>

<%= form_for(@alumni_data) do |f| %>

<% if @editingAllowed %>

<%= text_field_tag "alum_id", @alum.id.to_s, type: 'hidden' %>
<%= text_field_tag "student_id", current_student_member.id, type: 'hidden' %>

<% end %>

<% temp = AlumniData.new %>

<% @alum.attributes.keys.each_with_index do |attribute, key| %>

<% if not temp.attributes.keys.to_a.find_index(attribute) %>

<% next %>

<% end %>

<% if key < 2 or attribute.humanize.include? "Created" or attribute.humanize.include? "Updated" or attribute.humanize.include? "Alumni" %>

<% next %>

<% end %>

<%= label_tag attribute %>

<% if @editingAllowed %>

<%= text_field_tag "alumni_data[" + attribute + "]", @alum.attributes[attribute].to_s %>

<% else %>

<%= text_field_tag "alumni_data[" + attribute + "]", @alum.attributes[attribute].to_s, disabled: 'disabled' %>

<% end %>

<% end %>

<%= f.submit %>

<% end %>

<%= render "partials/paymentmodal" %>

<script type="text/javascript">
$(document).ready(function(){

	$(".setsearch li[data-val-integer=<%= @alum.search%>]").addClass("active");
	$(".setresponse li[data-val-integer=<%= @alum.response%>]").addClass("active");

	if("<%= @alum.response %>" === "paid" || "<%= @alum.response %>" === "verified"){

		var string = "<%= @alum.attributes['payment_details'].to_s %>";

		string = string.replace(/&quot;/g, '"');

		// console.log(string);

		paymentData = $.parseJSON(string);

		for(var key in paymentData){
			console.log(key);
			console.log(paymentData[key]);

			$("p#" + key).html($("p#" + key).html() + "<b>" + paymentData[key] + "</b>");
		}

		// console.log(paymentData);
	}
	else{
		$("#payment_details_div").css("display", "none");		
	}

	console.log("<%= @editingAllowed %>");

	<% if @editingAllowed %>	

	$(".setsearch li").on("click", function(){
		data = {
			id: "<%= @alum.id %>",
			setsearch: $(this).attr("data-val-integer")
		};

		$(".setsearch li").each(function(){
			$(this).removeClass("active");
		});

		$(this).addClass("active");

		$.post("/alumni/status/search", data);
	});

	$(".setresponse li").on("click", function(){
		data = {
			id: "<%= @alum.id %>",
			setresponse: $(this).attr("data-val-integer")
		};

		if(data.setresponse == 4){
			$("#payment_details_modal").modal('show');
		}

		else{

			$(".setresponse li").each(function(){
				$(this).removeClass("active");
			});

			$(this).addClass("active");

			$.post("/alumni/status/response", data);
		}
	});

	<% else %>

	$(".setsearch li, .setresponse li").each(function(){
		$(this).addClass("disabled");
	});

	<% end %>

	<% if coordinator_signed_in? %>

	$(".setresponse li[data-val=verified]").removeClass("disabled");

	$(".setresponse li").on("click", function(){
		data = {
			id: "<%= @alum.id %>",
			setresponse: $(this).attr("data-val-integer")
		};

		// coordinator can only change the status to verified.
		// other statuses are blocked for coordinators.

		if($(this).attr("data-val-integer") == "5"){
			$(".setresponse li").each(function(){
				$(this).removeClass("active");
			});

			$(this).addClass("active");

			$.post("/alumni/status/response", data);
		}
	});

	<% end %>

	// validate the call_next_at field
	// Expected: yyyy-mm-dd hh:mm

	$("form").on("submit", function(e){
		if(!$("#alumni_data_call_next_at").val().toString().match(/[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}/g)
			||
			$("#alumni_data_call_next_at").val().toString().length != 16 ){
			alert("The call next at field must obey yyyy-mm-dd hh:mm");
		e.preventDefault();
	}

	console.log($("#alumni_data_call_next_at").val().toString().length <= 16);

});

	// validate the payment details field

	$("#alumni_data_payment_details").css("display", "none");
	$("label[for=payment_details]").css("display", "none");

	getJSON = function(selector){
		data = new Object();
		arr = $(selector).serializeArray();
		console.log(arr);
		console.log(selector);
		for(var i=0; i<arr.length; ++i ){
			data[arr[i].name] = arr[i].value;
		}
		return data;
	};

	$("#payment_details_form").on("submit", function(e){
		console.log(getJSON("#payment_details_form"));
		form_data = getJSON("#payment_details_form");
		$("#alumni_data_payment_details").val(JSON.stringify(form_data));

		$("#payment_details_modal").modal("hide");

		$(".setresponse li").each(function(){
			$(this).removeClass("active");
		});

		$("[data-val=paid]").addClass("active");

		data = {
			id: "<%= @alum.id %>",
			setresponse: 4
		};

		$.post("/alumni/status/response", data);

		e.preventDefault();

		$("form.edit_alumni_data").submit();
	});

});
</script>